### ISSUE TITLE
Is there a way to get caller namespace ONLY, to be displayed in logs

### ISSUE THREAD

**Issue by sunnamed434** [pmetz-steelcase/Serilog.Enrichers.WithCaller#11]
[14:34:40 WRN] Test: (at Namespace)

**Comment by 0xced** [comment]
This should be addressed by #12. See also my [comment](https://github.com/pmetz-steelcase/Serilog.Enrichers.WithCaller/pull/10#issuecomment-1574916725) with a short sample code.

**Comment by sunnamed434** [comment]
I've solved this like [that](https://github.com/sunnamed434/BitMono/blob/784938f42b8ac722807d3c6d856216f6ba3c9e55/src/BitMono.Host/Modules/BitMonoModule.cs#L27), and also use improved version of the rolling file, which creates per every new instance of the application
