### ISSUE TITLE
Skip some frame method based on attribute.

### ISSUE THREAD

**Issue by deksan** [pmetz-steelcase/Serilog.Enrichers.WithCaller#13]
Hi,

Would it be possible to add an attribute of method type to prevent the output of this method in the Enrich method so it is skipped in the frame analysis ?
This attribute could add a string to override the name of the method used in the Caller String that is output if needed ?

Thanks !!

```c#
[System.AttributeUsage(System.AttributeTargets.Method)]
public class FilterEnricher : Attribute{
}
```
In the method          public void Enrich(LogEvent logEvent, ILogEventPropertyFactory propertyFactory)
Add some filter ?

```c#
if (method.MethodBase.GetCustomAttributes<FilterEnricher>().Any())
  continue;
if (method.SubMethodBase.GetCustomAttributes<FilterEnricher>().Any())
  continue;
```

Thanks.

**Comment by deksan** [comment]
Hi,
If you want I can submit a commit  request (if i find how :D ) ?
Thanks

**Comment by ppmetz** [comment]
project is no more maintained
