### ISSUE TITLE
Support for call stack depth parameter

### ISSUE THREAD

**Issue by Khaos66** [pmetz-steelcase/Serilog.Enrichers.WithCaller#2]
I'm looking for a way to add the current call stack to each log entry. This enricher is half way there.
So maybe you could add an additional depth parameter.
Something like that:
```C#
.Enrich.WithCaller(maxDepth: 3)
```
And then set {Caller} to simething like:
```C#
{Frame0} at {Frame1} at {Frame2}
```

That would be super helpfull <3 Thanks

**Comment by pmetz-steelcase** [comment]
Hello, 
so you can set it with the properties:
        public static int SkipFramesCount { get; set; } = 3;
        public static int MaxFrameCount { get; set; } = 128;

I'm building now a new version, where the maxDepth arument can be passed to WithCaller extension method

**Comment by Khaos66** [comment]
Hi. Thank you for the fast response!
I hope you understand me right.
```c#
public static int SkipFramesCount { get; set; } = 3;
public static int MaxFrameCount { get; set; } = 128;
``` 
Don't do the same...
I'll create a PR to show you what I mean ;)

**Comment by Khaos66** [comment]
See PR #3

**Comment by pmetz-steelcase** [comment]
Hi Khaos66, I created the branch call_stack_depth_parameter   including your pull request #3, and working on it - check if inside is what you suggested and run the test ...
cheers

**Comment by Khaos66** [comment]
I will do that later on and get back to you. Thanks!

**Comment by pmetz-steelcase** [comment]
@Khaos66 Hi, so there is the branch (tree) call_stack_depth_parameter  with your code and my code modifications. Please check it out if that's what you have in mind :)

Not sure how to give you access to that so you can commit directly on that branch.
cheers

**Comment by Khaos66** [comment]
Looking good =) plz publish

**Comment by pmetz-steelcase** [comment]
here it is https://www.nuget.org/packages/Serilog.Enrichers.WithCaller/1.2.0
cheers
