### ISSUE TITLE
Use 'Serilog' namespace for WithCaller extension

### ISSUE THREAD

**Issue by Khaos66** [pmetz-steelcase/Serilog.Enrichers.WithCaller#4]
Other serilog extensions just use the `Serilog` namespace.
This way consumers of this extension don't have to include another namespace using.
This is just about the extension in `LoggerCallerEnrichmentConfiguration.cs`. The enricher in `CallerEnricher.cs` can stay as is ;)

**Comment by pmetz-steelcase** [comment]
yes you are right - however for this I'm not sure if that's the best way, the namespace namespace "Serilog.Enrichers.WithCaller" does show that there is an option and I think it is also expected
I do not feel that this Enritcher is mature enough yet for this namespace :)

**Comment by Khaos66** [comment]
Ha, so humble... I get it. Maybe sometime then ;)

**Comment by pmetz-steelcase** [comment]
Hi Kaos66, so here it is: https://www.nuget.org/packages/Serilog.Enrichers.WithCaller/1.2.0
Cheers
